services:
  postgres:
    image: postgres:17
    container_name: idm_postgres-17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qweASD123*!
      - POSTGRES_DB=idm
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - smart-idm-network

  smart-idm:
    restart: always
    container_name: smart_idm
    build:
      context: .
      dockerfile: test.Dockerfile
    env_file:
      - .env.test
    ports:
      - "8080:8080"
    networks:
      - smart-idm-network
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - smart-idm-network

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - smart-idm-network

volumes:
  pgdata:
  grafana_data:

networks:
  smart-idm-network:
    driver: bridge