spring:
  application:
    name: smart-idm
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_idm}
    username: ${SPRING_DATASOURCE_USERNAME:smart_idm}
    password: ${SPRING_DATASOURCE_PASSWORD:smart_idm}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  thymeleaf:
    cache: false
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

server:
  port: 8080

logging:
  level:
    ru.mtkp.idm: info

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
