spring:
  application:
    name: smart-idm
  datasource:
    url: jdbc:postgresql://202.181.188.48:5433/idm
    username: postgres
    password: qweASD123*!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    ru.mtkp.idm: info
